# MySQL 8.0 공식 이미지를 기반으로 설정
FROM mysql:8.0

# 환경 변수 설정
ENV MYSQL_ROOT_PASSWORD=Hangle1234!
ENV MYSQL_DATABASE=hangledb
ENV MYSQL_USER=master
ENV MYSQL_PASSWORD=Hangle1234!

# 3306 포트 노출
EXPOSE 3306 

# MySQL 서버 실행
CMD ["mysqld"]